[package]
name = "obsidiantoreact"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
chrono-tz = "0.10.3"
clap = { version = "4.5.21", features = ["derive"] }
dotenvy = "0.15.7"
fxhash = "0.2.1"
